TICKETS = [
    {
        "id": "T1",
        "text": "My account was accessed from a location I don't recognize. Please help.",
        "tone": "neutral",
        "true_severity": "high",
        "true_action": "escalate",
        "trap_type": None,
    },
    {
        "id": "T2",
        "text": "THIS APP IS TRASH. I've been trying to change my profile theme for 20 minutes and it keeps reverting. USELESS.",
        "tone": "aggressive",
        "true_severity": "low",
        "true_action": "reply",
        "trap_type": "aggressive_trivial",
    },
    {
        "id": "T3",
        "text": "Hi, not urgent at all, but I noticed I was charged twice for my subscription this month. Probably just a glitch!",
        "tone": "polite",
        "true_severity": "high",
        "true_action": "escalate",
        "trap_type": "polite_critical",
    },
    {
        "id": "T4",
        "text": "URGENT: Please unsubscribe me from the weekly newsletter. Thank you.",
        "tone": "neutral",
        "true_severity": "low",
        "true_action": "ignore",
        "trap_type": "false_urgency",
    },
    {
        "id": "T5",
        "text": "I've been unable to log into my account for two days. Password reset emails are not arriving.",
        "tone": "neutral",
        "true_severity": "medium",
        "true_action": "reply",
        "trap_type": None,
    },
    {
        "id": "T6",
        "text": "Why is your verification process so broken?! I've submitted my ID three times and still can't verify my account.",
        "tone": "aggressive",
        "true_severity": "medium",
        "true_action": "reply",
        "trap_type": "aggressive_trivial",
    },
    {
        "id": "T7",
        "text": "Following up on ticket T3 — the double charge actually happened again this month. I now see three charges total. Still not urgent if you're busy.",
        "tone": "polite",
        "true_severity": "high",
        "true_action": "escalate",
        "trap_type": "context_dependent",
    },
    {
        "id": "T8",
        "text": "How do I export my data as a CSV? I couldn't find it in the settings.",
        "tone": "neutral",
        "true_severity": "low",
        "true_action": "reply",
        "trap_type": None,
    },
    {
        "id": "T9",
        "text": "So sorry to bother you! I think someone may have made a purchase using my account without my permission. No rush though.",
        "tone": "polite",
        "true_severity": "high",
        "true_action": "escalate",
        "trap_type": "polite_critical",
    },
    {
        "id": "T10",
        "text": "ABSOLUTELY RIDICULOUS. Your dark mode doesn't save between sessions. Fix this NOW.",
        "tone": "aggressive",
        "true_severity": "low",
        "true_action": "reply",
        "trap_type": "aggressive_trivial",
    },
    {
        "id": "T11",
        "text": "I was billed for a plan I downgraded from last month. Can you check my account?",
        "tone": "neutral",
        "true_severity": "medium",
        "true_action": "reply",
        "trap_type": None,
    },
    {
        "id": "T12",
        "text": "I reported suspicious activity two weeks ago (like ticket T1) and never heard back. The unauthorized access has now happened twice more.",
        "tone": "neutral",
        "true_severity": "high",
        "true_action": "escalate",
        "trap_type": "context_dependent",
    },
]
